### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by aberba** [captain-sensible/myweb#1]
How far do you want it to go? Check some php code I put up at https://github.com/aberba/php-classes

**Comment by captain-sensible** [comment]
Hi aberba had a look -will keep an eye on your repo! Just to clarify the aim of what i'm doing is to make it fairly easy for SME's . The web Almost completely runs out of the box. You try- just download zip onto your desktop , unzip it . Then using terminal cd to Desktop & use php built in server : $php -S localhost:8000 -t  myweb-master or <name of folder if you chnaged it> web will be up & running at http://localhost:8000 you will be able to submit a new blog entry & submit comments because the database is embedded (its sqlite & part of download) php coders should be able to hack since apart from fatfree structure i'm just using simple object O  php classes.
